### NEW TESTS
### Get all users
GET http://localhost:3030/users

### Create user
POST http://localhost:3030/users/createuser
Content-Type: application/json

{
    "intraId": 54345,
    "username": "laubeboi",
    "wins": 5,
    "losses": 4
}

### TEST CREATE 5 USERS
GET http://localhost:3030/profile/test/createusers
Content-Type: application/json

### TEST CREATE RELATIONSHIPS
GET http://localhost:3030/profile/test/createfriendships
Content-Type: application/json