GET http://localhost:3030/users

### Create User
POST http://localhost:3030/users
Content-Type: application/json

{
    "intraId": 4,
    "username": "testing_boi",
    "displayname": "testingtoy",
    "picture": "laube.jpg",
    "wins": 4,
    "losses": 6
}


### Get protected user profile
GET http://localhost:3030/users/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImxhdWJlIiwic3ViIjoxLCJpYXQiOjE2NjMxMTY5NTB9.njS7PcgacMYpMz5GbFS_tP82NosRm_XIhzxqaXxYYIA
